apiVersion: v1
kind: Service
metadata: 
  labels:
    run: "{{ .Release.Name }}-client"
    chart: "{{ .Chart.Name}}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
  name: "{{ .Release.Name }}-client"
spec:
  type: ClusterIP
  selector:
    component: "{{ .Release.Name }}-client"
  ports:
    - port: 3000
      targetPort: 3000